-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assessment_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessmentid uuid NOT NULL,
  userid uuid NOT NULL,
  score integer NOT NULL,
  percentage numeric,
  passed boolean,
  answers jsonb,
  timetaken integer,
  attemptnumber integer DEFAULT 1,
  completedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT assessment_results_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_results_assessmentid_fkey FOREIGN KEY (assessmentid) REFERENCES public.assessments(id),
  CONSTRAINT assessment_results_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid NOT NULL,
  lessonid uuid,
  title text NOT NULL,
  description text,
  type text DEFAULT 'quiz'::text CHECK (type = ANY (ARRAY['quiz'::text, 'assessment'::text, 'final_exam'::text])),
  passingscore integer DEFAULT 70,
  questions jsonb,
  totalquestions integer DEFAULT 0,
  duration integer DEFAULT 30,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT assessments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.auto_send_rule_execution_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_id uuid NOT NULL,
  user_id uuid NOT NULL,
  notification_id uuid,
  execution_status character varying DEFAULT 'sent'::character varying CHECK (execution_status::text = ANY (ARRAY['sent'::character varying, 'failed'::character varying, 'skipped'::character varying]::text[])),
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auto_send_rule_execution_log_pkey PRIMARY KEY (id),
  CONSTRAINT auto_send_rule_execution_log_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.notification_auto_send_rules(id),
  CONSTRAINT auto_send_rule_execution_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT auto_send_rule_execution_log_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid,
  lessonid uuid,
  assignmentid uuid,
  userid uuid,
  title text NOT NULL,
  description text,
  eventtype text DEFAULT 'other'::text CHECK (eventtype = ANY (ARRAY['deadline'::text, 'class'::text, 'assignment'::text, 'exam'::text, 'other'::text])),
  startdate timestamp with time zone NOT NULL,
  enddate timestamp with time zone,
  isallday boolean DEFAULT false,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.career_paths (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_role text NOT NULL,
  target_role text NOT NULL,
  description text,
  skill_requirements jsonb DEFAULT '[]'::jsonb,
  created_by text DEFAULT 'admin'::text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT career_paths_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certificate_cleanup_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  certificate_id uuid NOT NULL,
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  course_title text,
  certificate_enabled boolean,
  issued_at timestamp without time zone,
  deleted_at timestamp without time zone DEFAULT now(),
  reason text,
  CONSTRAINT certificate_cleanup_log_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_cleanup_log_certificate_id_fkey FOREIGN KEY (certificate_id) REFERENCES public.certificates(id),
  CONSTRAINT certificate_cleanup_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT certificate_cleanup_log_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.certificate_signature_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  designation text NOT NULL UNIQUE,
  signature_image_url text,
  signature_text text,
  is_enabled boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  CONSTRAINT certificate_signature_settings_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_signature_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.certificate_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  certificate_id uuid NOT NULL,
  signature_id uuid NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  signature_name text,
  signature_designation text,
  signature_text text,
  signature_image_url text,
  CONSTRAINT certificate_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_signatures_certificate_fkey FOREIGN KEY (certificate_id) REFERENCES public.certificates(id),
  CONSTRAINT certificate_signatures_signature_fkey FOREIGN KEY (signature_id) REFERENCES public.certificate_signature_settings(id)
);
CREATE TABLE public.certificate_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_name character varying NOT NULL UNIQUE,
  description text,
  background_image_url text NOT NULL,
  placeholder_config jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT false,
  display_order integer DEFAULT 0,
  width integer DEFAULT 3125,
  height integer DEFAULT 2209,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT certificate_templates_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  course_id uuid,
  issued_at timestamp with time zone DEFAULT now(),
  signature_ids ARRAY DEFAULT '{}'::text[],
  signatures_data jsonb DEFAULT '[]'::jsonb,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  template_id uuid,
  CONSTRAINT certificates_pkey PRIMARY KEY (id),
  CONSTRAINT certificates_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT certificates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id)
);
CREATE TABLE public.community_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  postid uuid NOT NULL,
  userid uuid NOT NULL,
  username text NOT NULL,
  useravatar text,
  content text NOT NULL,
  likes integer DEFAULT 0,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT community_comments_pkey PRIMARY KEY (id),
  CONSTRAINT community_comments_postid_fkey FOREIGN KEY (postid) REFERENCES public.community_posts(id),
  CONSTRAINT community_comments_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.community_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  postid uuid NOT NULL,
  userid uuid NOT NULL,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT community_likes_pkey PRIMARY KEY (id),
  CONSTRAINT community_likes_postid_fkey FOREIGN KEY (postid) REFERENCES public.community_posts(id),
  CONSTRAINT community_likes_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.community_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid,
  userid uuid NOT NULL,
  username text NOT NULL,
  useravatar text,
  title text NOT NULL,
  content text NOT NULL,
  category text DEFAULT 'general'::text,
  views integer DEFAULT 0,
  likes integer DEFAULT 0,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  image_url text,
  CONSTRAINT community_posts_pkey PRIMARY KEY (id),
  CONSTRAINT community_posts_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.concerns_tickets (
  id uuid NOT NULL DEFAULT auth.uid(),
  user_id uuid NOT NULL,
  user_email text NOT NULL,
  full_name text NOT NULL,
  category text NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  priority text DEFAULT 'normal'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_notes text,
  resolved_at timestamp with time zone,
  CONSTRAINT concerns_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT concerns_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.course_acknowledgements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  block_id text NOT NULL,
  policy_title text,
  signature text NOT NULL,
  acknowledged_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT course_acknowledgements_pkey PRIMARY KEY (id),
  CONSTRAINT course_acknowledgements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT course_acknowledgements_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_acknowledgements_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.course_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  courseid uuid NOT NULL,
  assigned_by uuid NOT NULL,
  is_mandatory boolean DEFAULT false,
  due_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_visible boolean DEFAULT true,
  CONSTRAINT course_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT course_assignments_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT course_assignments_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id),
  CONSTRAINT course_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.course_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid NOT NULL,
  userid uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT course_feedback_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id),
  CONSTRAINT course_feedback_userid_fkey FOREIGN KEY (userid) REFERENCES public.profiles(id)
);
CREATE TABLE public.course_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid NOT NULL,
  userid uuid NOT NULL,
  username text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  title text,
  review text,
  helpful integer DEFAULT 0,
  unhelpful integer DEFAULT 0,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT course_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT course_reviews_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  category text NOT NULL,
  instructorid uuid NOT NULL,
  instructorname text NOT NULL,
  thumbnail text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['published'::text, 'draft'::text])),
  level text DEFAULT 'beginner'::text CHECK (level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  duration integer DEFAULT 0,
  totalstudents integer DEFAULT 0,
  averagerating numeric DEFAULT 0,
  completionrate integer DEFAULT 0,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  prerequisites text,
  language text DEFAULT 'English'::text,
  is_mandatory boolean DEFAULT false,
  course_type text NOT NULL DEFAULT 'regular'::text,
  certificate_enabled boolean NOT NULL DEFAULT true,
  is_hidden boolean DEFAULT false,
  template_id uuid,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_instructorid_fkey FOREIGN KEY (instructorid) REFERENCES auth.users(id),
  CONSTRAINT courses_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  courseid uuid NOT NULL,
  progress integer DEFAULT 0,
  completed boolean DEFAULT false,
  hoursspent integer DEFAULT 0,
  lastaccessedat timestamp with time zone,
  enrolledat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  completedat timestamp with time zone,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_mandatory boolean DEFAULT false,
  assigned_at timestamp with time zone,
  assigned_by uuid,
  due_date timestamp with time zone,
  last_activity timestamp without time zone,
  enrollment_reminder_sent boolean DEFAULT false,
  inactivity_reminder_sent boolean DEFAULT false,
  deadline_reminder_sent boolean DEFAULT false,
  completed_at timestamp with time zone,
  retake_count integer DEFAULT 0,
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id),
  CONSTRAINT enrollments_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.external_assessment_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  assessment_id uuid NOT NULL,
  score numeric,
  cefr_level text,
  certificate_url text,
  result_url text,
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  verified_at timestamp with time zone,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_remarks text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT external_assessment_results_pkey PRIMARY KEY (id),
  CONSTRAINT external_assessment_results_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.user_external_assessments(id),
  CONSTRAINT external_assessment_results_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.external_assessments(id),
  CONSTRAINT external_assessment_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.external_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  provider text NOT NULL,
  external_url text NOT NULL,
  duration integer NOT NULL,
  attempt_limit integer DEFAULT 1,
  passing_criteria text,
  certificate_required boolean DEFAULT true,
  instructions text,
  thumbnail_url text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  score_mapping jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT external_assessments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flashcard_color_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL UNIQUE,
  instructor_id uuid NOT NULL,
  card_front_gradient_start text DEFAULT '#3498db'::text,
  card_front_gradient_end text DEFAULT '#2980b9'::text,
  card_back_gradient_start text DEFAULT '#2ecc71'::text,
  card_back_gradient_end text DEFAULT '#27ae60'::text,
  flip_icon_color text DEFAULT '#ffffff'::text,
  apply_to_all boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT flashcard_color_settings_pkey PRIMARY KEY (id),
  CONSTRAINT flashcard_color_settings_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT flashcard_color_settings_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.flashcard_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  flashcard_id uuid NOT NULL,
  flashcard_set_id uuid NOT NULL,
  is_completed boolean DEFAULT false,
  review_count integer DEFAULT 0,
  easy_count integer DEFAULT 0,
  difficult_count integer DEFAULT 0,
  last_reviewed_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT flashcard_progress_pkey PRIMARY KEY (id),
  CONSTRAINT flashcard_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.flashcard_set_completion (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  flashcard_set_id uuid NOT NULL,
  is_completed boolean DEFAULT false,
  completed_cards integer DEFAULT 0,
  total_cards integer DEFAULT 0,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT flashcard_set_completion_pkey PRIMARY KEY (id),
  CONSTRAINT flashcard_set_completion_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.flashcard_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  total_cards integer DEFAULT 0,
  ai_generated_count integer DEFAULT 0,
  max_ai_cards integer DEFAULT 50,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT flashcard_sets_pkey PRIMARY KEY (id),
  CONSTRAINT flashcard_sets_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT flashcard_sets_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.flashcards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  flashcard_set_id uuid NOT NULL,
  front text NOT NULL,
  back text NOT NULL,
  order integer NOT NULL,
  is_ai_generated boolean DEFAULT false,
  difficulty text DEFAULT 'medium'::text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  tags ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT flashcards_pkey PRIMARY KEY (id),
  CONSTRAINT flashcards_flashcard_set_id_fkey FOREIGN KEY (flashcard_set_id) REFERENCES public.flashcard_sets(id)
);
CREATE TABLE public.journey_modules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  journey_id uuid,
  title text NOT NULL,
  type text CHECK (type = ANY (ARRAY['Micro-Learning Module'::text, 'Classroom Module'::text, 'General feedback'::text, 'Course'::text])),
  course_id uuid,
  duration text,
  image_url text,
  provider text,
  sequence_order integer,
  unlock_days_after_start integer DEFAULT 0,
  CONSTRAINT journey_modules_pkey PRIMARY KEY (id),
  CONSTRAINT journey_modules_journey_id_fkey FOREIGN KEY (journey_id) REFERENCES public.learning_journeys(id),
  CONSTRAINT journey_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.leaderboard (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL UNIQUE,
  username text NOT NULL,
  useravatar text,
  totalpoints integer DEFAULT 0,
  rank integer,
  coursescompleted integer DEFAULT 0,
  totalhours integer DEFAULT 0,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT leaderboard_pkey PRIMARY KEY (id),
  CONSTRAINT leaderboard_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.learning_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  courseid uuid NOT NULL,
  hoursspent integer DEFAULT 0,
  date date NOT NULL DEFAULT CURRENT_DATE,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  time_spent_seconds integer DEFAULT 0,
  CONSTRAINT learning_hours_pkey PRIMARY KEY (id),
  CONSTRAINT learning_hours_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.learning_journeys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  type text CHECK (type = ANY (ARRAY['Standard'::text, 'Drip'::text, 'Flexible'::text])),
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT learning_journeys_pkey PRIMARY KEY (id),
  CONSTRAINT learning_journeys_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.learning_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  course_id uuid,
  lesson_id uuid,
  session_start timestamp with time zone NOT NULL,
  session_end timestamp with time zone,
  duration_seconds integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  idle_time_seconds integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT learning_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT learning_sessions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT learning_sessions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.learning_transaction_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key text NOT NULL UNIQUE,
  userid uuid NOT NULL,
  lessonid uuid,
  courseid uuid,
  status text DEFAULT 'SUCCESS'::text CHECK (status = ANY (ARRAY['SUCCESS'::text, 'DUPLICATE'::text, 'ERROR'::text])),
  lesson_progress_id uuid,
  learning_hours_id uuid,
  createdat timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone,
  error_message text,
  client_ip inet,
  user_agent text,
  CONSTRAINT learning_transaction_log_pkey PRIMARY KEY (id),
  CONSTRAINT learning_transaction_log_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT learning_transaction_log_lessonid_fkey FOREIGN KEY (lessonid) REFERENCES public.lessons(id),
  CONSTRAINT learning_transaction_log_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id)
);
CREATE TABLE public.lesson_audio_cache (
  id bigint NOT NULL DEFAULT nextval('lesson_audio_cache_id_seq'::regclass),
  lesson_id uuid NOT NULL,
  block_id text NOT NULL,
  chunk_index integer NOT NULL DEFAULT 0,
  audio_url text NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['coqui'::text, 'piper'::text, 'browser'::text])),
  duration integer NOT NULL,
  file_path text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lesson_audio_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lesson_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  lessonid uuid NOT NULL,
  courseid uuid NOT NULL,
  completed boolean DEFAULT false,
  progress integer DEFAULT 0,
  lastaccessedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  completedat timestamp with time zone,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  time_spent_seconds integer DEFAULT 0,
  session_count integer DEFAULT 0,
  CONSTRAINT lesson_progress_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_progress_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.lesson_time_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  session_id uuid,
  time_spent_seconds integer NOT NULL DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  idempotency_key text UNIQUE,
  CONSTRAINT lesson_time_logs_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_time_logs_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT lesson_time_logs_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT lesson_time_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT lesson_time_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.learning_sessions(id)
);
CREATE TABLE public.lesson_tts_settings (
  id bigint NOT NULL DEFAULT nextval('lesson_tts_settings_id_seq'::regclass),
  lesson_id uuid NOT NULL UNIQUE,
  course_id uuid NOT NULL UNIQUE,
  default_provider text NOT NULL DEFAULT 'coqui'::text CHECK (default_provider = ANY (ARRAY['coqui'::text, 'piper'::text, 'browser'::text])),
  fallback_provider text NOT NULL DEFAULT 'piper'::text CHECK (fallback_provider = ANY (ARRAY['coqui'::text, 'piper'::text, 'browser'::text])),
  lecture_quality text NOT NULL DEFAULT 'high'::text CHECK (lecture_quality = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  summary_quality text NOT NULL DEFAULT 'medium'::text CHECK (summary_quality = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  voice_gender text NOT NULL DEFAULT 'female'::text CHECK (voice_gender = ANY (ARRAY['male'::text, 'female'::text])),
  auto_pause_enabled boolean DEFAULT true,
  cache_audio boolean DEFAULT true,
  preload_audio boolean DEFAULT false,
  default_speed numeric DEFAULT 1.0,
  min_speed numeric DEFAULT 0.5,
  max_speed numeric DEFAULT 2.0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lesson_tts_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid NOT NULL,
  module_title text NOT NULL,
  module_order integer NOT NULL,
  title text NOT NULL,
  type text DEFAULT 'text'::text CHECK (type = ANY (ARRAY['text'::text, 'pdf'::text, 'video'::text, 'quiz'::text, 'flashcard'::text])),
  content text,
  description text,
  duration integer DEFAULT 0,
  islocked boolean DEFAULT false,
  order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  duration_minutes integer DEFAULT 0,
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id)
);
CREATE TABLE public.module_learning_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  moduleid uuid NOT NULL,
  userid uuid NOT NULL,
  totalhourslearned integer DEFAULT 0,
  completedlessons integer DEFAULT 0,
  totallessons integer DEFAULT 0,
  completionpercentage numeric DEFAULT 0,
  lastaccessedat timestamp with time zone,
  completedat timestamp with time zone,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT module_learning_stats_pkey PRIMARY KEY (id),
  CONSTRAINT module_learning_stats_moduleid_fkey FOREIGN KEY (moduleid) REFERENCES public.courses(id),
  CONSTRAINT module_learning_stats_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.notification_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scheduled_notification_id uuid,
  user_id uuid,
  notification_id uuid,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['sent'::character varying, 'viewed'::character varying, 'clicked'::character varying, 'failed'::character varying, 'bounced'::character varying, 'deleted'::character varying]::text[])),
  details jsonb DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  CONSTRAINT notification_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT notification_audit_log_scheduled_notification_id_fkey FOREIGN KEY (scheduled_notification_id) REFERENCES public.scheduled_notifications(id),
  CONSTRAINT notification_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notification_audit_log_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.notification_auto_send_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  trigger_type character varying NOT NULL CHECK (trigger_type::text = ANY (ARRAY['task_pending'::character varying, 'course_due'::character varying, 'assignment_overdue'::character varying, 'low_engagement'::character varying, 'inactive_user'::character varying]::text[])),
  trigger_params jsonb DEFAULT '{}'::jsonb,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'reminder'::character varying CHECK (type::text = ANY (ARRAY['general'::character varying, 'course'::character varying, 'assignment'::character varying, 'system'::character varying, 'announcement'::character varying, 'reminder'::character varying]::text[])),
  image_url text,
  link_url text,
  link_label character varying,
  priority integer DEFAULT 2 CHECK (priority >= 1 AND priority <= 5),
  send_after_days integer NOT NULL DEFAULT 1,
  send_before_days integer,
  max_sends_per_user integer DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_auto_send_rules_pkey PRIMARY KEY (id),
  CONSTRAINT notification_auto_send_rules_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  target_condition text,
  target_condition_details jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  total_recipients integer DEFAULT 0,
  sent_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT notification_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT notification_campaigns_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'general'::character varying CHECK (type::text = ANY (ARRAY['general'::character varying, 'course'::character varying, 'assignment'::character varying, 'system'::character varying, 'announcement'::character varying]::text[])),
  image_url text,
  link_url text,
  link_label character varying,
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 5),
  metadata jsonb DEFAULT '{}'::jsonb,
  is_template boolean DEFAULT false,
  template_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT notification_drafts_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  course_id uuid,
  message_type character varying NOT NULL,
  status character varying DEFAULT 'sent'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  sent_at timestamp without time zone,
  delivered_at timestamp without time zone,
  read_at timestamp without time zone,
  whatsapp_message_id text,
  error_message text,
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notification_logs_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  course_notifications boolean DEFAULT true,
  assignment_notifications boolean DEFAULT true,
  system_notifications boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  course_id uuid,
  message_type character varying NOT NULL,
  status character varying DEFAULT 'queued'::character varying,
  priority integer DEFAULT 1,
  retry_count integer DEFAULT 0,
  error_message text,
  template_params jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  processing_started_at timestamp without time zone,
  sent_at timestamp without time zone,
  CONSTRAINT notification_queue_pkey PRIMARY KEY (id),
  CONSTRAINT notification_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notification_queue_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'general'::character varying CHECK (type::text = ANY (ARRAY['general'::character varying, 'course'::character varying, 'assignment'::character varying, 'system'::character varying, 'announcement'::character varying]::text[])),
  image_url text,
  link_url text,
  link_label character varying,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 5),
  sender_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_deleted boolean DEFAULT false,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  fullname text,
  role text DEFAULT 'student'::text CHECK (role = ANY (ARRAY['learner'::text, 'admin'::text, 'instructor'::text, 'manager'::text])),
  avatarurl text,
  bio text,
  department text,
  joindate timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  user_id text,
  mobile_number text,
  user_status text DEFAULT 'Active'::text,
  preferred_language text,
  allowed_views ARRAY,
  company text,
  designation text,
  employment_type text,
  industry text,
  leadership_role text,
  location text,
  persona text,
  team text,
  manager_id uuid,
  manager_name text,
  manager_mapping boolean,
  employee_grade text,
  LinkedInPartnerAccess text,
  phone_number text,
  whatsapp_opt_in boolean DEFAULT true,
  notification_preferences jsonb DEFAULT '{"enrollment": true, "new_course": false, "certificate": true, "weekly_summary": false, "deadline_reminder": true, "inactivity_reminder": true}'::jsonb,
  linkedin_profile_url text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quiz_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  courseid uuid NOT NULL,
  assessmentid uuid NOT NULL,
  quiztitle text NOT NULL,
  pointsearned integer NOT NULL DEFAULT 0,
  totalpoints integer NOT NULL DEFAULT 0,
  percentage numeric,
  passed boolean DEFAULT false,
  answers jsonb,
  timetaken integer,
  attemptnumber integer DEFAULT 1,
  completedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_results_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_results_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT quiz_results_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id),
  CONSTRAINT quiz_results_assessmentid_fkey FOREIGN KEY (assessmentid) REFERENCES public.assessments(id)
);
CREATE TABLE public.quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  courseid uuid NOT NULL,
  lessonid uuid NOT NULL,
  title text NOT NULL,
  description text,
  type text DEFAULT 'quiz'::text CHECK (type = ANY (ARRAY['quiz'::text, 'assessment'::text, 'final_exam'::text])),
  passingscore integer DEFAULT 70,
  totalpoints integer DEFAULT 100,
  duration integer DEFAULT 30,
  questions jsonb DEFAULT '[]'::jsonb,
  totalquestions integer DEFAULT 0,
  isactive boolean DEFAULT true,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT quizzes_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id),
  CONSTRAINT quizzes_lessonid_fkey FOREIGN KEY (lessonid) REFERENCES public.lessons(id)
);
CREATE TABLE public.reconciliation_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  courseid uuid,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['DISCREPANCY'::text, 'MISSING_SESSION'::text, 'FLOATING_POINT_ERROR'::text, 'OVERCOUNTING'::text])),
  severity text DEFAULT 'WARNING'::text CHECK (severity = ANY (ARRAY['INFO'::text, 'WARNING'::text, 'CRITICAL'::text])),
  expected_seconds integer,
  actual_seconds integer,
  discrepancy_seconds integer,
  status text DEFAULT 'OPEN'::text CHECK (status = ANY (ARRAY['OPEN'::text, 'ACKNOWLEDGED'::text, 'RESOLVED'::text])),
  resolved_at timestamp without time zone,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  resolved_by uuid,
  CONSTRAINT reconciliation_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT reconciliation_alerts_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT reconciliation_alerts_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id),
  CONSTRAINT reconciliation_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.scheduled_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  draft_id uuid,
  admin_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'general'::character varying CHECK (type::text = ANY (ARRAY['general'::character varying, 'course'::character varying, 'assignment'::character varying, 'system'::character varying, 'announcement'::character varying]::text[])),
  image_url text,
  link_url text,
  link_label character varying,
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 5),
  metadata jsonb DEFAULT '{}'::jsonb,
  scheduled_for timestamp with time zone NOT NULL,
  is_recurring boolean DEFAULT false,
  recurrence_pattern character varying CHECK (recurrence_pattern::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'once'::character varying]::text[])),
  recurrence_end_date timestamp with time zone,
  recipient_type character varying DEFAULT 'all'::character varying CHECK (recipient_type::text = ANY (ARRAY['all'::character varying, 'users'::character varying, 'departments'::character varying, 'roles'::character varying, 'custom'::character varying]::text[])),
  recipient_users ARRAY DEFAULT '{}'::uuid[],
  recipient_departments ARRAY DEFAULT '{}'::text[],
  recipient_roles ARRAY DEFAULT '{}'::text[],
  recipient_filters jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'sent'::character varying, 'cancelled'::character varying, 'failed'::character varying]::text[])),
  sent_at timestamp with time zone,
  failed_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_notifications_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.notification_drafts(id),
  CONSTRAINT scheduled_notifications_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.skill_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  skillid uuid NOT NULL,
  visible boolean DEFAULT true,
  hidden boolean DEFAULT false,
  assignedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  expiry_date date,
  CONSTRAINT skill_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT skill_assignments_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT skill_assignments_skillid_fkey FOREIGN KEY (skillid) REFERENCES public.skills(id)
);
CREATE TABLE public.skill_course_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  skillid uuid NOT NULL,
  courseid uuid NOT NULL,
  required boolean DEFAULT false,
  visible boolean DEFAULT true,
  hidden boolean DEFAULT false,
  createdby text DEFAULT 'admin'::text,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  expiry_date date,
  generated_by_ai boolean DEFAULT false,
  ai_generated_at timestamp with time zone,
  CONSTRAINT skill_course_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT skill_course_mappings_skillid_fkey FOREIGN KEY (skillid) REFERENCES public.skills(id),
  CONSTRAINT skill_course_mappings_courseid_fkey FOREIGN KEY (courseid) REFERENCES public.courses(id)
);
CREATE TABLE public.skill_families (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  createdby text DEFAULT 'admin'::text,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  icon text,
  CONSTRAINT skill_families_pkey PRIMARY KEY (id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  family text NOT NULL,
  description text,
  createdby text DEFAULT 'admin'::text,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  type text DEFAULT 'technical'::text CHECK (type = ANY (ARRAY['technical'::text, 'soft_skills'::text, 'business'::text, 'management'::text, 'creative'::text, 'communication'::text, 'data_science'::text])),
  CONSTRAINT skills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL,
  badgename text NOT NULL,
  badgeicon text,
  description text,
  unlockedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.user_career_paths (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  career_path_id uuid NOT NULL,
  source_role_name text NOT NULL,
  target_role_name text NOT NULL,
  readiness_percentage numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'In Progress'::text CHECK (status = ANY (ARRAY['In Progress'::text, 'Ready for Promotion'::text, 'Completed'::text])),
  assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  target_date timestamp with time zone,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_career_paths_pkey PRIMARY KEY (id),
  CONSTRAINT user_career_paths_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_career_paths_career_path_id_fkey FOREIGN KEY (career_path_id) REFERENCES public.career_paths(id)
);
CREATE TABLE public.user_external_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  assessment_id uuid NOT NULL,
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'in_progress'::text, 'submitted'::text, 'evaluated'::text])),
  assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  valid_until timestamp with time zone,
  attempt_count integer DEFAULT 0,
  start_time timestamp with time zone,
  expected_end_time timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_external_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT user_external_assessments_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.external_assessments(id),
  CONSTRAINT user_external_assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_journey_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  journey_id uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  status text DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text])),
  progress integer DEFAULT 0,
  start_date timestamp with time zone,
  CONSTRAINT user_journey_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_journey_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_journey_assignments_journey_id_fkey FOREIGN KEY (journey_id) REFERENCES public.learning_journeys(id),
  CONSTRAINT user_journey_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_journey_module_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_journey_id uuid,
  module_id uuid,
  status text DEFAULT 'locked'::text CHECK (status = ANY (ARRAY['locked'::text, 'unlocked'::text, 'completed'::text])),
  unlock_date timestamp with time zone,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT user_journey_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_journey_module_progress_user_journey_id_fkey FOREIGN KEY (user_journey_id) REFERENCES public.user_journey_assignments(id),
  CONSTRAINT user_journey_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.journey_modules(id)
);
CREATE TABLE public.user_skill_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  skill_id uuid NOT NULL,
  skill_name text NOT NULL,
  course_level text NOT NULL CHECK (course_level = ANY (ARRAY['Beginner'::text, 'Intermediate'::text, 'Advanced'::text, 'beginner'::text, 'intermediate'::text, 'advanced'::text, 'BEGINNER'::text, 'INTERMEDIATE'::text, 'ADVANCED'::text])),
  course_id uuid NOT NULL,
  course_title text,
  percentage_achieved numeric NOT NULL DEFAULT 0,
  completed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_skill_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_skill_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_skill_achievements_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id),
  CONSTRAINT user_skill_achievements_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.user_statistics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userid uuid NOT NULL UNIQUE,
  totalcoursesenrolled integer DEFAULT 0,
  coursescompleted integer DEFAULT 0,
  totallearninghours integer DEFAULT 0,
  currentstreak integer DEFAULT 0,
  totalpoints integer DEFAULT 0,
  leaderboardrank integer,
  lastactivityat timestamp with time zone,
  createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT user_statistics_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.v_pass_rate (
  case numeric
);
CREATE TABLE public.v_skill_coverage (
  case numeric
);
CREATE TABLE public.whatsapp_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  meta_template_name character varying NOT NULL,
  message_type character varying NOT NULL,
  body text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT whatsapp_templates_pkey PRIMARY KEY (id)
);